### ISSUE TITLE
Erros in UWP

### ISSUE THREAD

**Issue by leandromsilveira** [Microsoft/SmartHotel360-mobile-desktop-apps#19] opened 2018-03-14 05:56 UTC
How can I fix these problems below?

Severity	Code	Description	Project	File	Line	Suppression State
Error		Type universe cannot resolve assembly: System.Diagnostics.Contracts, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.	SmartHotel.Clients.UWP			

Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot resolve Assembly or Windows Metadata file 'System.Diagnostics.Contracts.dll'	SmartHotel.Clients.UWP	C:\Projects\SmartHotel360-mobile-desktop-apps\src\SmartHotel.Clients\SmartHotel.Clients.UWP\SmartHotel.Clients.UWP.csproj

**Comment by dasanagu** [comment] 2018-03-14 22:50
Hi @leandromsilveira we are not able to reproduce the issue. Could you please give us more details also which version of Visual Studio are you using? Thanks and sorry for the inconvenience.

**Comment by bradygmsft** [comment] 2018-03-22 05:28
ping to @leandromsilveira - are you still seeing this? We tried to reproduce it and had no success doing so.

**Comment by dasanagu** [comment] 2018-09-19 17:01
This was fixed with a latest update.

**Closed by dasanagu** 2018-09-19 17:01 UTC
Labels: no repro
