### ISSUE TITLE
Compile errors in iOS project

### ISSUE THREAD

**Issue by ManishJainGitHubUser** [Microsoft/SmartHotel360-mobile-desktop-apps#12] opened 2018-01-01 19:59 UTC
/SmartHotel360-mobile-desktop-apps-master/src/SmartHotel.Clients/SmartHotel.Clients.iOS/AppDelegate.cs(63,63): Error CS0246: The type or namespace name `PlatformParameters' could not be found. Are you missing `Microsoft.IdentityModel.Clients.ActiveDirectory' using directive? (CS0246) (SmartHotel.Clients.iOS)
/Users/manishjain/Downloadsmaster/src/SmartHotel.Clients/SmartHotel.Clients.iOS/AppDelegate.cs(17,17): Error CS0012: The type `Microsoft.Identity.Client.PublicClientApplication' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Microsoft.Identity.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' (CS0012) (SmartHotel.Clients.iOS)
/SmartHotel360-mobile-desktop-apps-master/src/SmartHotel.Clients/SmartHotel.Clients.iOS/AppDelegate.cs(38,38): Error CS0023: The `.' operator cannot be applied to operand of type `Microsoft.Identity.Client.PublicClientApplication' (CS0023) (SmartHotel.Clients.iOS)

--
Package 'Microsoft.Identity.Client.1.1.0-preview' already exists in project 'SmartHotel.Clients.iOS'

**Comment by jsuarezruiz** [comment] 2018-01-09 10:43
Hello,

It seems that the Microsoft.Identity.Client package is missing in the iOS project.

![image](https://user-images.githubusercontent.com/6755973/34716761-1f49459c-f531-11e7-9cc0-2205a081fd4b.png)

What version of Visual Studio and Xamarin do you use?

I have tested on Windows and macOS with the latest versions of Visual Studio for macOS and Visual Studio Community 2017 for Windows.
![image](https://user-images.githubusercontent.com/6755973/34716938-a4086736-f531-11e7-928f-8bb0bee56578.png)
With a little more information we will fix the problem :)

**Comment by dasanagu** [comment] 2018-01-30 18:59
Due we don't have any other comment, we are going to proceed closing the issue. Please feel free to contact us or reopen the issue is you need further assistance with this or other issues.

**Closed by dasanagu** 2018-01-30 18:59 UTC
